version: '3'
services:
  ledsite:
    build: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    

  envoy:
    build: Dockerfile.envoy
    ports:
      - "8080:8080"
    depends_on:
      - ledsite
