apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
     run.googleapis.com/launch-stage: BETA
  name: enel453-led-display
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1 #or gen2
        run.googleapis.com/container-dependencies: "{envoy: [ledsite]}"
    spec:
      containers:
      - image: gcr.io/atkin-1/enel453_labs_envoy:latest
        name: envoy
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      - image: gcr.io/atkin-1/enel453_labs:latest
        name: ledsite
        env:
          - name: PORT
            value: "5000"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      